[package]
name = "multicall"
version = "0.1.0"
edition = "2023_10"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.4.1"


[[target.starknet-contract]]
casm = true
# Enable allowed libfuncs validation.
allowed-libfuncs = true
allowed-libfuncs-list.name = "all"

[tool.fmt]
sort-module-level-items = true
