[workspace]
members = [
    "crates/*",
]

[workspace.dependencies]
starknet = "2.4.1"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.13.1" }
sncast_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.13.1" }


[workspace.tool.snforge]
exit_first = true

[workspace.tool.fmt]
sort-module-level-items = true
